### ISSUE TITLE
Enable wi-fi and set time only on INIT or user input

### ISSUE THREAD

**Issue by baronunread** [qewer33/qpaperOS#6]
Maybe the second part isn't even needed but it could be a good feature in case we want to enable wi-fi when we wanna check something, but for now there are no features using it. 

Instead of opening the wi-fi connection multiple times let's open it only once on the INIT and use configTime to obtain the current time.

One thing of note: in the current code we're not actually checking that the wi-fi has actually connected before calling the configTime method. This makes it happen that sometimes the configTime just doesn't work at all. Sometimes configTime can also just fail. 

I'm testing a PR that does this in the setup:

- checks if we're in the INIT state
- enables wifi, checks if connected, if not waits
- does the rest of the setup
- if we're in the INIT state, sets the RTC with configTime
- added another NTP server option to configTime
- checks if getLocalTime works otherwise delays and tries again

@qewer33 what do you think? The RTC is pretty accurate and works mid sleep so we don't really need to add multiple connections to the wi-fi

**Comment by qewer33** [comment]
The RTC is actually not even remotely accurate, I remember getting more than 1-2 minutes of drift per day. That's why the watch attempts to update the time via wifi every wake up.

**Comment by baronunread** [comment]
every wake up seems a bit too much especially considering that on every deep sleep it's basically running setup all over again
I think that syncing maybe once or twice per day might be good enough no?

**Comment by baronunread** [comment]
Ok it's been about a day and I can see it drifted apart a lot... It's about 5-6 minutes now
I would say every 6 hours, or maybe even 12 hours might be acceptable for a wifi update.

Btw @qewer33 this is an early assumption but after having removed the wifi.begin from every single wake up (except for the INIT) it looks like the battery life is much better overall, it's still stuck at 100% with the battery percentage

**Comment by qewer33** [comment]
> Btw @qewer33 this is an early assumption but after having removed the wifi.begin from every single wake up (except for the INIT) it looks like the battery life is much better overall, it's still stuck at 100% with the battery percentage

Interesting, if doing that actually improves battery life then it was a definitely a huge oversight on my part. I'll try to test it myself when I can.

**Comment by baronunread** [comment]
It seems much better yeah. I'm almost ready to publish a branch with it, with a couple more things :)
